version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_USER: postgres
      POSTGRES_DB: test-bmstu
    ports:
      - 5432:5432
  db-test:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_USER: postgres
      POSTGRES_DB: test
    ports:
      - 9000:5432